include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/core/database/*.drift.dart"

  language:
    strict-casts: true
    strict-raw-types: true
  errors:
    todo: ignore

linter:
  rules:
    always_use_package_imports: true
    avoid_relative_lib_imports: true
